const images = {
    arizonacardinals: require('./assets/logos/arizonacardinals.png'),
    atlantafalcons: require('./assets/logos/atlantafalcons.png'),
    baltimoreravens: require('./assets/logos/baltimoreravens.png'),
    buffalobills: require('./assets/logos/buffalobills.png'),
    carolinapanthers: require('./assets/logos/carolinapanthers.png'),
    chicagobears: require('./assets/logos/chicagobears.png'),
    cincinnatibengals: require('./assets/logos/cincinnatibengals.png'),
    clevelandbrowns: require('./assets/logos/clevelandbrowns.png'),
    dallascowboys: require('./assets/logos/dallascowboys.png'),
    denverbroncos: require('./assets/logos/denverbroncos.png'),
    detroitlions: require('./assets/logos/detroitlions.png'),
    greenbaypackers: require('./assets/logos/greenbaypackers.png'),
    houstontexans: require('./assets/logos/houstontexans.png'),
    indianapoliscolts: require('./assets/logos/indianapoliscolts.png'),
    jacksonvillejaguars: require('./assets/logos/jacksonvillejaguars.png'),
    kansascitychiefs: require('./assets/logos/kansascitychiefs.png'),
    lasvegasraiders: require('./assets/logos/lasvegasraiders.png'),
    losangeleschargers: require('./assets/logos/losangeleschargers.png'),
    losangelesrams: require('./assets/logos/losangelesrams.png'),
    miamidolphins: require('./assets/logos/miamidolphins.png'),
    minnesotavikings: require('./assets/logos/minnesotavikings.png'),
    newenglandpatriots: require('./assets/logos/newenglandpatriots.png'),
    neworleanssaints: require('./assets/logos/neworleanssaints.png'),
    newyorkgiants: require('./assets/logos/newyorkgiants.png'),
    newyorkjets: require('./assets/logos/newyorkjets.png'),
    philadelphiaeagles: require('./assets/logos/philadelphiaeagles.png'),
    pittsburghsteelers: require('./assets/logos/pittsburghsteelers.png'),
    sanfrancisco49ers: require('./assets/logos/sanfrancisco49ers.png'),
    seattleseahawks: require('./assets/logos/seattleseahawks.png'),
    tampabaybuccaneers: require('./assets/logos/tampabaybuccaneers.png'),
    tennesseetitans: require('./assets/logos/tennesseetitans.png'),
    washingtonfootballteam: require('./assets/logos/washingtonfootballteam.png'),
    moon: require('./assets/moon.png'),
    sun: require('./assets/sun.png'),
    downarrow: require('./assets/downarrow.png'),
    uparrow: require('./assets/uparrow.png'),
};

export default images;